services:
  worker:
    image: shubhtistic/sonclarus-worker:v1
    container_name: sonclarus-worker
    network_mode: "host"  # use the host
    env_file: 
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
