services:
  alembic:
    image: shubhtistic/fastapi-image:v1
    container_name: sonclarus-migrator
    env_file: .env
    network_mode : "host"
    command: alembic upgrade head

  api:
    image: shubhtistic/fastapi-image:v1
    container_name: sonclarus-api
    "network_mode": "host"
    env_file: .env
    depends_on:
      alembic:
        condition: service_completed_successfully