"""add_new_indexes

Revision ID: 7e9fc5aeaaed
Revises: d619200dc144
Create Date: 2026-05-08 08:44:00.645956

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "7e9fc5aeaaed"
down_revision: Union[str, Sequence[str], None] = "d619200dc144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_user_and_created_at", "job", ["user_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_refreshtoken_hashed_token"),
        "refreshtoken",
        ["hashed_token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshtoken_hashed_token"), table_name="refreshtoken")
    op.drop_index("idx_user_and_created_at", table_name="job")
    # ### end Alembic commands ###
