"""changes in refresh token db

Revision ID: b726ef6e29bb
Revises: 4a873f5565b7
Create Date: 2026-02-17 13:15:30.543534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b726ef6e29bb'
down_revision: Union[str, Sequence[str], None] = '4a873f5565b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtoken', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refreshtoken', 'revoked')
    # ### end Alembic commands ###
